import type { Lang } from "./languages";

export type BodyRegion = {
  id: string;
  label: Record<Lang, string>;
  phrase: Record<Lang, string>;
};

export const BODY_REGIONS: BodyRegion[] = [
  {
    id: "head",
    label: {
      en: "Head",
      es: "Cabeza",
      zh: "头",
      ar: "الرأس",
      fr: "Tête",
      pt: "Cabeça",
      vi: "Đầu",
      ko: "머리",
      ht: "Tèt",
      hi: "सिर",
    },
    phrase: {
      en: "It hurts here: my head.",
      es: "Me duele aquí: la cabeza.",
      zh: "这里疼：我的头。",
      ar: "يؤلمني هنا: رأسي.",
      fr: "J’ai mal ici : à la tête.",
      pt: "Dói aqui: a cabeça.",
      vi: "Tôi đau ở đây: đầu.",
      ko: "여기가 아파요: 머리.",
      ht: "Li fè m mal isit la: tèt mwen.",
      hi: "यहाँ दर्द है: सिर।",
    },
  },
  {
    id: "neck",
    label: {
      en: "Neck",
      es: "Cuello",
      zh: "脖子",
      ar: "العنق",
      fr: "Cou",
      pt: "Pescoço",
      vi: "Cổ",
      ko: "목",
      ht: "Kou",
      hi: "गर्दन",
    },
    phrase: {
      en: "It hurts here: my neck.",
      es: "Me duele aquí: el cuello.",
      zh: "这里疼：脖子。",
      ar: "يؤلمني هنا: عنقي.",
      fr: "J’ai mal ici : au cou.",
      pt: "Dói aqui: o pescoço.",
      vi: "Tôi đau ở đây: cổ.",
      ko: "여기가 아파요: 목.",
      ht: "Li fè m mal isit la: kou mwen.",
      hi: "यहाँ दर्द है: गर्दन।",
    },
  },
  {
    id: "chest",
    label: {
      en: "Chest",
      es: "Pecho",
      zh: "胸口",
      ar: "الصدر",
      fr: "Poitrine",
      pt: "Peito",
      vi: "Ngực",
      ko: "가슴",
      ht: "Pwatrin",
      hi: "सीना",
    },
    phrase: {
      en: "It hurts here: my chest.",
      es: "Me duele aquí: el pecho.",
      zh: "这里疼：胸口。",
      ar: "يؤلمني هنا: صدري.",
      fr: "J’ai mal ici : à la poitrine.",
      pt: "Dói aqui: o peito.",
      vi: "Tôi đau ở đây: ngực.",
      ko: "여기가 아파요: 가슴.",
      ht: "Li fè m mal isit la: pwatrin mwen.",
      hi: "यहाँ दर्द है: सीना।",
    },
  },
  {
    id: "abdomen",
    label: {
      en: "Abdomen",
      es: "Abdomen",
      zh: "腹部",
      ar: "البطن",
      fr: "Ventre",
      pt: "Abdômen",
      vi: "Bụng",
      ko: "배",
      ht: "Vant",
      hi: "पेट",
    },
    phrase: {
      en: "It hurts here: my abdomen.",
      es: "Me duele aquí: el abdomen.",
      zh: "这里疼：肚子。",
      ar: "يؤلمني هنا: بطني.",
      fr: "J’ai mal ici : au ventre.",
      pt: "Dói aqui: a barriga.",
      vi: "Tôi đau ở đây: bụng.",
      ko: "여기가 아파요: 배.",
      ht: "Li fè m mal isit la: vant mwen.",
      hi: "यहाँ दर्द है: पेट।",
    },
  },
  {
    id: "back",
    label: {
      en: "Back",
      es: "Espalda",
      zh: "背部",
      ar: "الظهر",
      fr: "Dos",
      pt: "Costas",
      vi: "Lưng",
      ko: "등",
      ht: "Do",
      hi: "पीठ",
    },
    phrase: {
      en: "It hurts here: my back.",
      es: "Me duele aquí: la espalda.",
      zh: "这里疼：后背。",
      ar: "يؤلمني هنا: ظهري.",
      fr: "J’ai mal ici : au dos.",
      pt: "Dói aqui: as costas.",
      vi: "Tôi đau ở đây: lưng.",
      ko: "여기가 아파요: 등.",
      ht: "Li fè m mal isit la: do mwen.",
      hi: "यहाँ दर्द है: पीठ।",
    },
  },
  {
    id: "left-arm",
    label: {
      en: "Left arm",
      es: "Brazo izquierdo",
      zh: "左臂",
      ar: "الذراع اليسرى",
      fr: "Bras gauche",
      pt: "Braço esquerdo",
      vi: "Cánh tay trái",
      ko: "왼팔",
      ht: "Bra gòch",
      hi: "बायाँ हाथ",
    },
    phrase: {
      en: "It hurts here: my left arm.",
      es: "Me duele aquí: el brazo izquierdo.",
      zh: "这里疼：左臂。",
      ar: "يؤلمني هنا: ذراعي اليسرى.",
      fr: "J’ai mal ici : au bras gauche.",
      pt: "Dói aqui: o braço esquerdo.",
      vi: "Tôi đau ở đây: cánh tay trái.",
      ko: "여기가 아파요: 왼팔.",
      ht: "Li fè m mal isit la: bra gòch mwen.",
      hi: "यहाँ दर्द है: बायाँ हाथ।",
    },
  },
  {
    id: "right-arm",
    label: {
      en: "Right arm",
      es: "Brazo derecho",
      zh: "右臂",
      ar: "الذراع اليمنى",
      fr: "Bras droit",
      pt: "Braço direito",
      vi: "Cánh tay phải",
      ko: "오른팔",
      ht: "Bra dwat",
      hi: "दायाँ हाथ",
    },
    phrase: {
      en: "It hurts here: my right arm.",
      es: "Me duele aquí: el brazo derecho.",
      zh: "这里疼：右臂。",
      ar: "يؤلمني هنا: ذراعي اليمنى.",
      fr: "J’ai mal ici : au bras droit.",
      pt: "Dói aqui: o braço direito.",
      vi: "Tôi đau ở đây: cánh tay phải.",
      ko: "여기가 아파요: 오른팔.",
      ht: "Li fè m mal isit la: bra dwat mwen.",
      hi: "यहाँ दर्द है: दायाँ हाथ।",
    },
  },
  {
    id: "left-leg",
    label: {
      en: "Left leg",
      es: "Pierna izquierda",
      zh: "左腿",
      ar: "الساق اليسرى",
      fr: "Jambe gauche",
      pt: "Perna esquerda",
      vi: "Chân trái",
      ko: "왼다리",
      ht: "Janm gòch",
      hi: "बायाँ पैर",
    },
    phrase: {
      en: "It hurts here: my left leg.",
      es: "Me duele aquí: la pierna izquierda.",
      zh: "这里疼：左腿。",
      ar: "يؤلمني هنا: ساقي اليسرى.",
      fr: "J’ai mal ici : à la jambe gauche.",
      pt: "Dói aqui: a perna esquerda.",
      vi: "Tôi đau ở đây: chân trái.",
      ko: "여기가 아파요: 왼다리.",
      ht: "Li fè m mal isit la: janm gòch mwen.",
      hi: "यहाँ दर्द है: बायाँ पैर।",
    },
  },
  {
    id: "right-leg",
    label: {
      en: "Right leg",
      es: "Pierna derecha",
      zh: "右腿",
      ar: "الساق اليمنى",
      fr: "Jambe droite",
      pt: "Perna direita",
      vi: "Chân phải",
      ko: "오른다리",
      ht: "Janm dwat",
      hi: "दायाँ पैर",
    },
    phrase: {
      en: "It hurts here: my right leg.",
      es: "Me duele aquí: la pierna derecha.",
      zh: "这里疼：右腿。",
      ar: "يؤلمني هنا: ساقي اليمنى.",
      fr: "J’ai mal ici : à la jambe droite.",
      pt: "Dói aqui: a perna direita.",
      vi: "Tôi đau ở đây: chân phải.",
      ko: "여기가 아파요: 오른다리.",
      ht: "Li fè m mal isit la: janm dwat mwen.",
      hi: "यहाँ दर्द है: दायाँ पैर।",
    },
  },
];
