import type { Lang } from "./languages";

export const SCENARIOS = [
  { id: "greet", label: "Greeting" },
  { id: "emergency", label: "Emergency" },
  { id: "symptoms", label: "Symptoms" },
  { id: "pain", label: "Pain" },
  { id: "allergies", label: "Allergies" },
  { id: "meds", label: "Medicines" },
  { id: "history", label: "History" },
  { id: "consent", label: "Consent" },
  { id: "discharge", label: "Discharge" },
  { id: "pharmacy", label: "Pharmacy" },
] as const;

export type ScenarioId = (typeof SCENARIOS)[number]["id"];

export type Phrase = {
  id: string;
  scenario: ScenarioId;
  speaker: "clinician" | "patient" | "either";
  text: Record<Lang, string>;
};

export const PHRASES: Phrase[] = [
  {
    id: "g1",
    scenario: "greet",
    speaker: "clinician",
    text: {
      en: "Hello. I am your nurse.",
      es: "Hola. Soy su enfermera / enfermero.",
      zh: "您好。我是您的护士。",
      ar: "مرحباً. أنا الممرض / الممرضة الخاص بك.",
      fr: "Bonjour. Je suis votre infirmier / infirmière.",
      pt: "Olá. Eu sou seu enfermeiro / sua enfermeira.",
      vi: "Xin chào. Tôi là điều dưỡng của bạn.",
      ko: "안녕하세요. 저는 담당 간호사입니다.",
      ht: "Bonjou. Mwen se enfimyè ou.",
      hi: "नमस्ते। मैं आपकी नर्स हूँ।",
    },
  },
  {
    id: "g2",
    scenario: "greet",
    speaker: "clinician",
    text: {
      en: "Hello. I am your doctor.",
      es: "Hola. Soy su médico / médica.",
      zh: "您好。我是您的医生。",
      ar: "مرحباً. أنا طبيبك.",
      fr: "Bonjour. Je suis votre médecin.",
      pt: "Olá. Eu sou seu médico / sua médica.",
      vi: "Xin chào. Tôi là bác sĩ của bạn.",
      ko: "안녕하세요. 저는 담당 의사입니다.",
      ht: "Bonjou. Mwen se doktè ou.",
      hi: "नमस्ते। मैं आपके डॉक्टर हूँ।",
    },
  },
  {
    id: "g3",
    scenario: "greet",
    speaker: "clinician",
    text: {
      en: "What is your name?",
      es: "¿Cómo se llama?",
      zh: "您叫什么名字？",
      ar: "ما اسمك؟",
      fr: "Comment vous appelez-vous ?",
      pt: "Qual é o seu nome?",
      vi: "Tên bạn là gì?",
      ko: "성함이 어떻게 되세요?",
      ht: "Ki jan ou rele?",
      hi: "आपका नाम क्या है?",
    },
  },
  {
    id: "g4",
    scenario: "greet",
    speaker: "clinician",
    text: {
      en: "What is your date of birth?",
      es: "¿Cuál es su fecha de nacimiento?",
      zh: "您的出生日期是哪天？",
      ar: "ما تاريخ ميلادك؟",
      fr: "Quelle est votre date de naissance ?",
      pt: "Qual é a sua data de nascimento?",
      vi: "Ngày sinh của bạn là gì?",
      ko: "생년월일이 어떻게 되세요?",
      ht: "Ki dat nesans ou?",
      hi: "आपकी जन्म तिथि क्या है?",
    },
  },
  {
    id: "g5",
    scenario: "greet",
    speaker: "clinician",
    text: {
      en: "Do you need an interpreter?",
      es: "¿Necesita un intérprete?",
      zh: "您需要口译员吗？",
      ar: "هل تحتاج إلى مترجم؟",
      fr: "Avez-vous besoin d’un interprète ?",
      pt: "Você precisa de um intérprete?",
      vi: "Bạn có cần thông dịch viên không?",
      ko: "통역이 필요하신가요?",
      ht: "Èske ou bezwen yon entèprèt?",
      hi: "क्या आपको दुभाषिए की ज़रूरत है?",
    },
  },
  {
    id: "g6",
    scenario: "greet",
    speaker: "either",
    text: {
      en: "Please speak slowly.",
      es: "Por favor, hable despacio.",
      zh: "请说慢一点。",
      ar: "من فضلك تكلم ببطء.",
      fr: "Parlez lentement, s’il vous plaît.",
      pt: "Por favor, fale devagar.",
      vi: "Xin hãy nói chậm.",
      ko: "천천히 말씀해 주세요.",
      ht: "Tanpri pale dousman.",
      hi: "कृपया धीरे बोलें।",
    },
  },
  {
    id: "g7",
    scenario: "greet",
    speaker: "patient",
    text: {
      en: "I do not speak English well.",
      es: "No hablo inglés bien.",
      zh: "我英语说得不好。",
      ar: "لا أتحدث الإنجليزية جيداً.",
      fr: "Je ne parle pas bien anglais.",
      pt: "Eu não falo inglês bem.",
      vi: "Tôi nói tiếng Anh không giỏi.",
      ko: "영어를 잘 못해요.",
      ht: "Mwen pa pale angle byen.",
      hi: "मैं अंग्रेज़ी अच्छी तरह नहीं बोलता/बोलती।",
    },
  },
  {
    id: "e1",
    scenario: "emergency",
    speaker: "patient",
    text: {
      en: "I need a doctor now.",
      es: "Necesito un médico ahora.",
      zh: "我现在需要医生。",
      ar: "أحتاج إلى طبيب الآن.",
      fr: "J’ai besoin d’un médecin tout de suite.",
      pt: "Preciso de um médico agora.",
      vi: "Tôi cần bác sĩ ngay bây giờ.",
      ko: "지금 당장 의사가 필요해요.",
      ht: "Mwen bezwen yon doktè kounye a.",
      hi: "मुझे अभी डॉक्टर चाहिए।",
    },
  },
  {
    id: "e2",
    scenario: "emergency",
    speaker: "patient",
    text: {
      en: "I cannot breathe.",
      es: "No puedo respirar.",
      zh: "我喘不上气。",
      ar: "لا أستطيع التنفس.",
      fr: "Je n’arrive pas à respirer.",
      pt: "Não consigo respirar.",
      vi: "Tôi không thở được.",
      ko: "숨을 쉴 수가 없어요.",
      ht: "Mwen pa ka respire.",
      hi: "मैं साँस नहीं ले पा रहा/रही हूँ।",
    },
  },
  {
    id: "e3",
    scenario: "emergency",
    speaker: "patient",
    text: {
      en: "I have chest pain.",
      es: "Tengo dolor en el pecho.",
      zh: "我胸口痛。",
      ar: "لدي ألم في الصدر.",
      fr: "J’ai mal à la poitrine.",
      pt: "Estou com dor no peito.",
      vi: "Tôi đau ngực.",
      ko: "가슴이 아파요.",
      ht: "Mwen gen doulè nan pwatrin mwen.",
      hi: "मेरे सीने में दर्द है।",
    },
  },
  {
    id: "e4",
    scenario: "emergency",
    speaker: "patient",
    text: {
      en: "I am bleeding.",
      es: "Estoy sangrando.",
      zh: "我在出血。",
      ar: "أنا أنزف.",
      fr: "Je saigne.",
      pt: "Estou sangrando.",
      vi: "Tôi đang chảy máu.",
      ko: "피가 나요.",
      ht: "Mwen ap senyen.",
      hi: "मुझे खून बह रहा है।",
    },
  },
  {
    id: "e5",
    scenario: "emergency",
    speaker: "patient",
    text: {
      en: "I feel like I might faint.",
      es: "Siento que me voy a desmayar.",
      zh: "我觉得自己快要晕倒了。",
      ar: "أشعر أنني قد أُغمى علي.",
      fr: "J’ai l’impression que je vais m’évanouir.",
      pt: "Sinto que vou desmaiar.",
      vi: "Tôi cảm thấy như sắp ngất.",
      ko: "기절할 것 같아요.",
      ht: "Mwen santi m ka pedi konesans.",
      hi: "लगता है मैं बेहोश हो जाऊँगा/जाऊँगी।",
    },
  },
  {
    id: "e6",
    scenario: "emergency",
    speaker: "clinician",
    text: {
      en: "Stay still. Help is coming.",
      es: "Quédese quieto. Ya viene la ayuda.",
      zh: "请不要动。救援马上到。",
      ar: "ابقَ ثابتاً. المساعدة قادمة.",
      fr: "Ne bougez pas. Les secours arrivent.",
      pt: "Fique quieto. A ajuda está chegando.",
      vi: "Hãy nằm yên. Trợ giúp đang đến.",
      ko: "움직이지 마세요. 도움이 오고 있습니다.",
      ht: "Rete trankil. Èd la ap vini.",
      hi: "हिलें नहीं। मदद आ रही है।",
    },
  },
  {
    id: "s1",
    scenario: "symptoms",
    speaker: "clinician",
    text: {
      en: "Where does it hurt?",
      es: "¿Dónde le duele?",
      zh: "哪里疼？",
      ar: "أين يؤلمك؟",
      fr: "Où avez-vous mal ?",
      pt: "Onde dói?",
      vi: "Bạn đau ở đâu?",
      ko: "어디가 아프세요?",
      ht: "Ki kote li fè ou mal?",
      hi: "दर्द कहाँ है?",
    },
  },
  {
    id: "s2",
    scenario: "symptoms",
    speaker: "clinician",
    text: {
      en: "When did this start?",
      es: "¿Cuándo empezó esto?",
      zh: "这是什么时候开始的？",
      ar: "متى بدأ هذا؟",
      fr: "Quand cela a-t-il commencé ?",
      pt: "Quando isso começou?",
      vi: "Việc này bắt đầu khi nào?",
      ko: "언제부터 시작됐나요?",
      ht: "Kilè sa te kòmanse?",
      hi: "यह कब शुरू हुआ?",
    },
  },
  {
    id: "s3",
    scenario: "symptoms",
    speaker: "clinician",
    text: {
      en: "Does it come and go?",
      es: "¿Va y viene?",
      zh: "是一阵一阵的吗？",
      ar: "هل يأتي ويذهب؟",
      fr: "Est-ce que ça va et vient ?",
      pt: "Vem e vai?",
      vi: "Nó đến rồi đi à?",
      ko: "아팠다 안 아팠다 하나요?",
      ht: "Èske li vini epi ale?",
      hi: "क्या दर्द आता-जाता है?",
    },
  },
  {
    id: "s4",
    scenario: "symptoms",
    speaker: "clinician",
    text: {
      en: "Do you have a fever?",
      es: "¿Tiene fiebre?",
      zh: "您发烧吗？",
      ar: "هل لديك حمى؟",
      fr: "Avez-vous de la fièvre ?",
      pt: "Você está com febre?",
      vi: "Bạn có sốt không?",
      ko: "열이 있나요?",
      ht: "Èske ou gen lafyèv?",
      hi: "क्या आपको बुखार है?",
    },
  },
  {
    id: "s5",
    scenario: "symptoms",
    speaker: "clinician",
    text: {
      en: "Are you nauseated?",
      es: "¿Tiene náuseas?",
      zh: "您觉得恶心吗？",
      ar: "هل تشعر بالغثيان؟",
      fr: "Avez-vous des nausées ?",
      pt: "Você está com náusea?",
      vi: "Bạn có cảm thấy buồn nôn không?",
      ko: "속이 메스꺼우신가요?",
      ht: "Èske ou santi kè sote?",
      hi: "क्या आपको जी मिचला रहा है?",
    },
  },
  {
    id: "s6",
    scenario: "symptoms",
    speaker: "clinician",
    text: {
      en: "Have you vomited?",
      es: "¿Ha vomitado?",
      zh: "您吐过吗？",
      ar: "هل تقيأت؟",
      fr: "Avez-vous vomi ?",
      pt: "Você vomitou?",
      vi: "Bạn đã nôn chưa?",
      ko: "구토를 하셨나요?",
      ht: "Èske ou vomi?",
      hi: "क्या आपको उल्टी हुई है?",
    },
  },
  {
    id: "s7",
    scenario: "symptoms",
    speaker: "clinician",
    text: {
      en: "Are you dizzy?",
      es: "¿Está mareado?",
      zh: "您头晕吗？",
      ar: "هل تشعر بالدوار؟",
      fr: "Avez-vous des vertiges ?",
      pt: "Você está tonto?",
      vi: "Bạn có bị chóng mặt không?",
      ko: "어지러우신가요?",
      ht: "Èske tèt ou vire?",
      hi: "क्या आपको चक्कर आ रहे हैं?",
    },
  },
  {
    id: "s8",
    scenario: "symptoms",
    speaker: "patient",
    text: {
      en: "It started last night.",
      es: "Empezó anoche.",
      zh: "昨晚开始的。",
      ar: "بدأ الليلة الماضية.",
      fr: "Ça a commencé hier soir.",
      pt: "Começou ontem à noite.",
      vi: "Nó bắt đầu tối qua.",
      ko: "어젯밤부터 시작됐어요.",
      ht: "Li te kòmanse yè swa.",
      hi: "यह कल रात शुरू हुआ।",
    },
  },
  {
    id: "p1",
    scenario: "pain",
    speaker: "clinician",
    text: {
      en: "On a scale of 0 to 10, how bad is the pain?",
      es: "En una escala de 0 a 10, ¿qué tan fuerte es el dolor?",
      zh: "如果 0 到 10 分，疼痛有多严重？",
      ar: "على مقياس من 0 إلى 10، ما شدة الألم؟",
      fr: "Sur une échelle de 0 à 10, à quel point avez-vous mal ?",
      pt: "De 0 a 10, quão forte está a dor?",
      vi: "Trên thang điểm 0 đến 10, cơn đau nặng đến mức nào?",
      ko: "0에서 10까지, 통증이 얼마나 심한가요?",
      ht: "Sou yon echèl 0 rive 10, ki jan doulè a fò?",
      hi: "0 से 10 के पैमाने पर दर्द कितना तेज़ है?",
    },
  },
  {
    id: "p2",
    scenario: "pain",
    speaker: "clinician",
    text: {
      en: "Is the pain sharp or dull?",
      es: "¿El dolor es agudo o sordo?",
      zh: "疼痛是刺痛还是闷痛？",
      ar: "هل الألم حاد أم خفيف؟",
      fr: "La douleur est-elle vive ou sourde ?",
      pt: "A dor é aguda ou surda?",
      vi: "Cơn đau nhói hay âm ỉ?",
      ko: "통증이 찌르는 듯한가요, 둔한가요?",
      ht: "Èske doulè a pwent oswa lou?",
      hi: "दर्द तेज़ चुभन वाला है या भारी-मंद?",
    },
  },
  {
    id: "p3",
    scenario: "pain",
    speaker: "clinician",
    text: {
      en: "Does the pain spread anywhere?",
      es: "¿El dolor se irradia a alguna parte?",
      zh: "疼痛会放射到别处吗？",
      ar: "هل ينتشر الألم إلى مكان آخر؟",
      fr: "La douleur irradie-t-elle ailleurs ?",
      pt: "A dor se espalha para algum lugar?",
      vi: "Cơn đau có lan sang chỗ khác không?",
      ko: "통증이 다른 곳으로 퍼지나요?",
      ht: "Èske doulè a gaye yon lòt kote?",
      hi: "क्या दर्द कहीं और फैलता है?",
    },
  },
  {
    id: "p4",
    scenario: "pain",
    speaker: "clinician",
    text: {
      en: "What makes it better?",
      es: "¿Qué lo alivia?",
      zh: "怎样会好一点？",
      ar: "ما الذي يخففه؟",
      fr: "Qu’est-ce qui soulage ?",
      pt: "O que alivia?",
      vi: "Điều gì làm dịu đi?",
      ko: "뭐가 하면 나아지나요?",
      ht: "Kisa ki fè l pi byen?",
      hi: "किससे आराम मिलता है?",
    },
  },
  {
    id: "p5",
    scenario: "pain",
    speaker: "clinician",
    text: {
      en: "What makes it worse?",
      es: "¿Qué lo empeora?",
      zh: "怎样会更疼？",
      ar: "ما الذي يزيده سوءاً؟",
      fr: "Qu’est-ce qui l’aggrave ?",
      pt: "O que piora?",
      vi: "Điều gì làm nặng hơn?",
      ko: "뭐가 하면 더 심해지나요?",
      ht: "Kisa ki fè l pi mal?",
      hi: "किससे दर्द बढ़ता है?",
    },
  },
  {
    id: "p6",
    scenario: "pain",
    speaker: "patient",
    text: {
      en: "The pain is a 7 out of 10.",
      es: "El dolor es un 7 de 10.",
      zh: "疼痛大概是 10 分里的 7 分。",
      ar: "الألم 7 من 10.",
      fr: "La douleur est à 7 sur 10.",
      pt: "A dor está em 7 de 10.",
      vi: "Cơn đau khoảng 7 trên 10.",
      ko: "통증은 10점 만점에 7점이에요.",
      ht: "Doulè a se 7 sou 10.",
      hi: "दर्द 10 में से 7 है।",
    },
  },
  {
    id: "a1",
    scenario: "allergies",
    speaker: "clinician",
    text: {
      en: "Do you have any allergies?",
      es: "¿Tiene alguna alergia?",
      zh: "您有过敏吗？",
      ar: "هل لديك أي حساسية؟",
      fr: "Avez-vous des allergies ?",
      pt: "Você tem alguma alergia?",
      vi: "Bạn có dị ứng gì không?",
      ko: "알레르기가 있으신가요?",
      ht: "Èske ou gen alèji?",
      hi: "क्या आपको कोई एलर्जी है?",
    },
  },
  {
    id: "a2",
    scenario: "allergies",
    speaker: "clinician",
    text: {
      en: "Are you allergic to any medicines?",
      es: "¿Es alérgico a algún medicamento?",
      zh: "您对什么药过敏吗？",
      ar: "هل لديك حساسية من أي أدوية؟",
      fr: "Êtes-vous allergique à des médicaments ?",
      pt: "Você é alérgico a algum medicamento?",
      vi: "Bạn có dị ứng với thuốc nào không?",
      ko: "약 알레르기가 있나요?",
      ht: "Èske ou alèjik ak okenn medikaman?",
      hi: "क्या आपको किसी दवा से एलर्जी है?",
    },
  },
  {
    id: "a3",
    scenario: "allergies",
    speaker: "clinician",
    text: {
      en: "Are you allergic to latex?",
      es: "¿Es alérgico al látex?",
      zh: "您对乳胶过敏吗？",
      ar: "هل لديك حساسية من اللاتكس؟",
      fr: "Êtes-vous allergique au latex ?",
      pt: "Você é alérgico a látex?",
      vi: "Bạn có dị ứng latex không?",
      ko: "라텍스 알레르기가 있나요?",
      ht: "Èske ou alèjik ak latèks?",
      hi: "क्या आपको लेटेक्स से एलर्जी है?",
    },
  },
  {
    id: "a4",
    scenario: "allergies",
    speaker: "clinician",
    text: {
      en: "What happens when you take it?",
      es: "¿Qué le pasa cuando lo toma?",
      zh: "吃了之后会怎样？",
      ar: "ماذا يحدث عندما تتناوله؟",
      fr: "Que se passe-t-il quand vous le prenez ?",
      pt: "O que acontece quando você toma?",
      vi: "Khi dùng thì bạn bị gì?",
      ko: "드시면 어떤 반응이 있나요?",
      ht: "Kisa k ap pase lè ou pran li?",
      hi: "लेने पर क्या होता है?",
    },
  },
  {
    id: "a5",
    scenario: "allergies",
    speaker: "patient",
    text: {
      en: "I am allergic to penicillin.",
      es: "Soy alérgico a la penicilina.",
      zh: "我对青霉素过敏。",
      ar: "لدي حساسية من البنسلين.",
      fr: "Je suis allergique à la pénicilline.",
      pt: "Sou alérgico à penicilina.",
      vi: "Tôi dị ứng với penicillin.",
      ko: "페니실린 알레르기가 있어요.",
      ht: "Mwen alèjik ak penisilin.",
      hi: "मुझे पेनिसिलिन से एलर्जी है।",
    },
  },
  {
    id: "m1",
    scenario: "meds",
    speaker: "clinician",
    text: {
      en: "What medicines do you take?",
      es: "¿Qué medicamentos toma?",
      zh: "您在吃哪些药？",
      ar: "ما الأدوية التي تتناولها؟",
      fr: "Quels médicaments prenez-vous ?",
      pt: "Que medicamentos você toma?",
      vi: "Bạn đang dùng thuốc gì?",
      ko: "어떤 약을 드시고 계세요?",
      ht: "Ki medikaman ou pran?",
      hi: "आप कौन-कौन सी दवाएँ लेते हैं?",
    },
  },
  {
    id: "m2",
    scenario: "meds",
    speaker: "clinician",
    text: {
      en: "Do you take blood thinners?",
      es: "¿Toma anticoagulantes?",
      zh: "您在吃抗凝血药吗？",
      ar: "هل تتناول أدوية تسييل الدم؟",
      fr: "Prenez-vous des anticoagulants ?",
      pt: "Você toma anticoagulantes?",
      vi: "Bạn có dùng thuốc làm loãng máu không?",
      ko: "혈액 응고 방지제를 드시나요?",
      ht: "Èske ou pran medikaman pou san pa gwose?",
      hi: "क्या आप ब्लड थिनर लेते हैं?",
    },
  },
  {
    id: "m3",
    scenario: "meds",
    speaker: "clinician",
    text: {
      en: "Have you taken this medicine today?",
      es: "¿Tomó esta medicina hoy?",
      zh: "今天吃过这个药了吗？",
      ar: "هل تناولت هذا الدواء اليوم؟",
      fr: "Avez-vous pris ce médicament aujourd’hui ?",
      pt: "Você tomou este medicamento hoje?",
      vi: "Hôm nay bạn đã uống thuốc này chưa?",
      ko: "오늘 이 약을 드셨나요?",
      ht: "Èske ou pran medikaman sa a jodi a?",
      hi: "क्या आज यह दवा ली है?",
    },
  },
  {
    id: "m4",
    scenario: "meds",
    speaker: "clinician",
    text: {
      en: "I will give you this medicine now.",
      es: "Le voy a dar esta medicina ahora.",
      zh: "我现在给您用这个药。",
      ar: "سأعطيك هذا الدواء الآن.",
      fr: "Je vais vous donner ce médicament maintenant.",
      pt: "Vou dar este medicamento agora.",
      vi: "Tôi sẽ cho bạn thuốc này bây giờ.",
      ko: "지금 이 약을 드리겠습니다.",
      ht: "Mwen pral ba ou medikaman sa a kounye a.",
      hi: "मैं आपको अभी यह दवा दूँगा/दूँगी।",
    },
  },
  {
    id: "m5",
    scenario: "meds",
    speaker: "patient",
    text: {
      en: "I take medicine for blood pressure.",
      es: "Tomo medicina para la presión.",
      zh: "我在吃降压药。",
      ar: "أتناول دواء للضغط.",
      fr: "Je prends un médicament pour la tension.",
      pt: "Tomo remédio para pressão.",
      vi: "Tôi uống thuốc huyết áp.",
      ko: "혈압약을 먹고 있어요.",
      ht: "Mwen pran medikaman pou tansyon.",
      hi: "मैं ब्लड प्रेशर की दवा लेता/लेती हूँ।",
    },
  },
  {
    id: "h1",
    scenario: "history",
    speaker: "clinician",
    text: {
      en: "Do you have diabetes?",
      es: "¿Tiene diabetes?",
      zh: "您有糖尿病吗？",
      ar: "هل لديك مرض السكري؟",
      fr: "Avez-vous du diabète ?",
      pt: "Você tem diabetes?",
      vi: "Bạn có bị tiểu đường không?",
      ko: "당뇨가 있으신가요?",
      ht: "Èske ou gen dyabèt?",
      hi: "क्या आपको मधुमेह है?",
    },
  },
  {
    id: "h2",
    scenario: "history",
    speaker: "clinician",
    text: {
      en: "Do you have high blood pressure?",
      es: "¿Tiene la presión alta?",
      zh: "您有高血压吗？",
      ar: "هل لديك ضغط دم مرتفع؟",
      fr: "Avez-vous de l’hypertension ?",
      pt: "Você tem pressão alta?",
      vi: "Bạn có bị cao huyết áp không?",
      ko: "고혈압이 있으신가요?",
      ht: "Èske ou gen tansyon wo?",
      hi: "क्या आपका रक्तचाप उच्च है?",
    },
  },
  {
    id: "h3",
    scenario: "history",
    speaker: "clinician",
    text: {
      en: "Have you had surgery before?",
      es: "¿Le han operado antes?",
      zh: "您以前做过手术吗？",
      ar: "هل أجريت عملية جراحية من قبل؟",
      fr: "Avez-vous déjà été opéré ?",
      pt: "Você já fez alguma cirurgia?",
      vi: "Bạn đã từng phẫu thuật chưa?",
      ko: "전에 수술을 받은 적 있나요?",
      ht: "Èske yo te deja opere ou?",
      hi: "क्या पहले कोई सर्जरी हुई है?",
    },
  },
  {
    id: "h4",
    scenario: "history",
    speaker: "clinician",
    text: {
      en: "Are you pregnant, or could you be pregnant?",
      es: "¿Está embarazada, o podría estarlo?",
      zh: "您怀孕了吗，或者有可能怀孕吗？",
      ar: "هل أنت حامل، أو قد تكونين حاملاً؟",
      fr: "Êtes-vous enceinte, ou pourriez-vous l’être ?",
      pt: "Você está grávida, ou pode estar?",
      vi: "Bạn có đang mang thai, hoặc có thể mang thai không?",
      ko: "임신 중이거나 임신 가능성이 있나요?",
      ht: "Èske ou ansent, oswa ou ta ka ansent?",
      hi: "क्या आप गर्भवती हैं, या हो सकती हैं?",
    },
  },
  {
    id: "h5",
    scenario: "history",
    speaker: "clinician",
    text: {
      en: "Do you smoke?",
      es: "¿Fuma?",
      zh: "您抽烟吗？",
      ar: "هل تدخن؟",
      fr: "Est-ce que vous fumez ?",
      pt: "Você fuma?",
      vi: "Bạn có hút thuốc không?",
      ko: "담배를 피우시나요?",
      ht: "Èske ou fimen?",
      hi: "क्या आप धूम्रपान करते हैं?",
    },
  },
  {
    id: "c1",
    scenario: "consent",
    speaker: "clinician",
    text: {
      en: "I need your permission to examine you.",
      es: "Necesito su permiso para examinarle.",
      zh: "我需要您的同意才能检查。",
      ar: "أحتاج إلى إذنك لفحصك.",
      fr: "J’ai besoin de votre accord pour vous examiner.",
      pt: "Preciso da sua permissão para examiná-lo.",
      vi: "Tôi cần sự đồng ý của bạn để khám.",
      ko: "진찰을 위해 동의가 필요합니다.",
      ht: "Mwen bezwen pèmisyon ou pou egzamine ou.",
      hi: "जांच के लिए आपकी अनुमति चाहिए।",
    },
  },
  {
    id: "c2",
    scenario: "consent",
    speaker: "clinician",
    text: {
      en: "I need to draw blood.",
      es: "Necesito extraerle sangre.",
      zh: "我需要抽血。",
      ar: "أحتاج إلى سحب دم.",
      fr: "Je dois vous prélever du sang.",
      pt: "Preciso coletar sangue.",
      vi: "Tôi cần lấy máu.",
      ko: "채혈이 필요합니다.",
      ht: "Mwen bezwen pran san.",
      hi: "मुझे खून का सैंपल लेना है।",
    },
  },
  {
    id: "c3",
    scenario: "consent",
    speaker: "clinician",
    text: {
      en: "I need to start an IV.",
      es: "Necesito colocarle una vía intravenosa.",
      zh: "我需要给您打静脉点滴。",
      ar: "أحتاج إلى تركيب محاليل وريدية.",
      fr: "Je dois poser une perfusion.",
      pt: "Preciso colocar um soro.",
      vi: "Tôi cần đặt đường truyền tĩnh mạch.",
      ko: "링거(정맥주사)를 맞혀야 합니다.",
      ht: "Mwen bezwen mete yon pèfizyon.",
      hi: "मुझे आईवी लगानी है।",
    },
  },
  {
    id: "c4",
    scenario: "consent",
    speaker: "clinician",
    text: {
      en: "Do you understand?",
      es: "¿Me entiende?",
      zh: "您明白吗？",
      ar: "هل تفهم؟",
      fr: "Est-ce que vous comprenez ?",
      pt: "Você entende?",
      vi: "Bạn hiểu không?",
      ko: "이해되셨나요?",
      ht: "Èske ou konprann?",
      hi: "क्या आप समझ गए?",
    },
  },
  {
    id: "c5",
    scenario: "consent",
    speaker: "clinician",
    text: {
      en: "You can say no.",
      es: "Puede decir que no.",
      zh: "您可以拒绝。",
      ar: "يمكنك أن ترفض.",
      fr: "Vous avez le droit de refuser.",
      pt: "Você pode dizer não.",
      vi: "Bạn có quyền từ chối.",
      ko: "거절하셔도 됩니다.",
      ht: "Ou ka di non.",
      hi: "आप मना कर सकते हैं।",
    },
  },
  {
    id: "c6",
    scenario: "consent",
    speaker: "patient",
    text: {
      en: "Yes, I agree.",
      es: "Sí, estoy de acuerdo.",
      zh: "好的，我同意。",
      ar: "نعم، أوافق.",
      fr: "Oui, je suis d’accord.",
      pt: "Sim, eu concordo.",
      vi: "Vâng, tôi đồng ý.",
      ko: "네, 동의합니다.",
      ht: "Wi, mwen dakò.",
      hi: "हाँ, मैं सहमत हूँ।",
    },
  },
  {
    id: "d1",
    scenario: "discharge",
    speaker: "clinician",
    text: {
      en: "You may go home today.",
      es: "Puede irse a casa hoy.",
      zh: "您今天可以回家了。",
      ar: "يمكنك العودة إلى المنزل اليوم.",
      fr: "Vous pouvez rentrer chez vous aujourd’hui.",
      pt: "Você pode ir para casa hoje.",
      vi: "Hôm nay bạn có thể về nhà.",
      ko: "오늘은 퇴원하셔도 됩니다.",
      ht: "Ou ka ale lakay ou jodi a.",
      hi: "आप आज घर जा सकते हैं।",
    },
  },
  {
    id: "d2",
    scenario: "discharge",
    speaker: "clinician",
    text: {
      en: "Take this medicine with food.",
      es: "Tome esta medicina con comida.",
      zh: "这个药要随餐服用。",
      ar: "تناول هذا الدواء مع الطعام.",
      fr: "Prenez ce médicament pendant le repas.",
      pt: "Tome este medicamento com comida.",
      vi: "Hãy uống thuốc này cùng với thức ăn.",
      ko: "이 약은 식사와 함께 드세요.",
      ht: "Pran medikaman sa a ak manje.",
      hi: "यह दवा भोजन के साथ लें।",
    },
  },
  {
    id: "d3",
    scenario: "discharge",
    speaker: "clinician",
    text: {
      en: "Come back if you get worse.",
      es: "Regrese si empeora.",
      zh: "如果病情加重请马上回来。",
      ar: "عد إذا ساءت حالتك.",
      fr: "Revenez si ça s’aggrave.",
      pt: "Volte se piorar.",
      vi: "Nếu nặng hơn thì hãy quay lại.",
      ko: "더 나빠지면 다시 오세요.",
      ht: "Tounen si ou vin pi mal.",
      hi: "अगर हालत बिगड़े तो वापस आएँ।",
    },
  },
  {
    id: "d4",
    scenario: "discharge",
    speaker: "clinician",
    text: {
      en: "Here are your papers.",
      es: "Aquí tiene sus papeles.",
      zh: "这是您的资料。",
      ar: "هذه أوراقك.",
      fr: "Voici vos papiers.",
      pt: "Aqui estão seus papéis.",
      vi: "Đây là giấy tờ của bạn.",
      ko: "서류 여기 있습니다.",
      ht: "Men papye ou yo.",
      hi: "ये आपके कागज़ हैं।",
    },
  },
  {
    id: "d5",
    scenario: "discharge",
    speaker: "clinician",
    text: {
      en: "Follow up with your doctor.",
      es: "Haga un seguimiento con su médico.",
      zh: "请复诊看您的医生。",
      ar: "راجع طبيبك للمتابعة.",
      fr: "Prenez rendez-vous de suivi avec votre médecin.",
      pt: "Faça o retorno com seu médico.",
      vi: "Hãy tái khám với bác sĩ của bạn.",
      ko: "담당 의사에게 추적 진료를 받으세요.",
      ht: "Ale wè doktè ou pou swivi.",
      hi: "अपने डॉक्टर से फॉलो-अप करें।",
    },
  },
  {
    id: "ph1",
    scenario: "pharmacy",
    speaker: "clinician",
    text: {
      en: "Take one tablet twice a day.",
      es: "Tome una pastilla dos veces al día.",
      zh: "每天两次，每次一片。",
      ar: "خذ قرصاً واحداً مرتين في اليوم.",
      fr: "Prenez un comprimé deux fois par jour.",
      pt: "Tome um comprimido duas vezes ao dia.",
      vi: "Uống một viên, ngày hai lần.",
      ko: "하루 두 번, 한 알씩 드세요.",
      ht: "Pran yon tablèt de fwa pa jou.",
      hi: "दिन में दो बार एक गोली लें।",
    },
  },
  {
    id: "ph2",
    scenario: "pharmacy",
    speaker: "clinician",
    text: {
      en: "Do not drink alcohol with this medicine.",
      es: "No tome alcohol con esta medicina.",
      zh: "服药期间不要饮酒。",
      ar: "لا تشرب الكحول مع هذا الدواء.",
      fr: "Ne buvez pas d’alcool avec ce médicament.",
      pt: "Não beba álcool com este medicamento.",
      vi: "Đừng uống rượu khi dùng thuốc này.",
      ko: "이 약을 드시는 동안 음주하지 마세요.",
      ht: "Pa bwè alkòl ak medikaman sa a.",
      hi: "इस दवा के साथ शराब न पिएँ।",
    },
  },
  {
    id: "ph3",
    scenario: "pharmacy",
    speaker: "clinician",
    text: {
      en: "This may make you sleepy.",
      es: "Esto puede darle sueño.",
      zh: "这个药可能会让您困。",
      ar: "قد يسبب هذا الدواء النعاس.",
      fr: "Cela peut vous rendre somnolent.",
      pt: "Isto pode causar sono.",
      vi: "Thuốc này có thể làm bạn buồn ngủ.",
      ko: "이 약은 졸음을 유발할 수 있습니다.",
      ht: "Sa ka fè ou dòmi.",
      hi: "इससे नींद आ सकती है।",
    },
  },
  {
    id: "ph4",
    scenario: "pharmacy",
    speaker: "patient",
    text: {
      en: "How many days should I take this?",
      es: "¿Cuántos días debo tomarlo?",
      zh: "这个药要吃几天？",
      ar: "كم يوماً يجب أن آخذه؟",
      fr: "Pendant combien de jours dois-je le prendre ?",
      pt: "Por quantos dias devo tomar?",
      vi: "Tôi phải uống bao nhiêu ngày?",
      ko: "며칠 동안 먹어야 하나요?",
      ht: "Konbyen jou mwen dwe pran li?",
      hi: "यह कितने दिनों तक लेनी है?",
    },
  },
  {
    id: "ph5",
    scenario: "pharmacy",
    speaker: "patient",
    text: {
      en: "Can I take this with my other medicines?",
      es: "¿Puedo tomarlo con mis otras medicinas?",
      zh: "可以和其他药一起吃吗？",
      ar: "هل يمكنني تناوله مع أدويتي الأخرى؟",
      fr: "Puis-je le prendre avec mes autres médicaments ?",
      pt: "Posso tomar com meus outros medicamentos?",
      vi: "Tôi có thể uống cùng các thuốc khác không?",
      ko: "다른 약과 같이 먹어도 되나요?",
      ht: "Èske m ka pran li ak lòt medikaman mwen yo?",
      hi: "क्या मैं इसे अपनी दूसरी दवाओं के साथ ले सकता/सकती हूँ?",
    },
  },
];

export function phrasesByScenario(id: ScenarioId) {
  return PHRASES.filter((p) => p.scenario === id);
}

export function scenarioLabel(id: ScenarioId) {
  return SCENARIOS.find((s) => s.id === id)?.label ?? id;
}

function normalize(s: string) {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .replace(/[^\p{L}\p{N}\s]/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function matchPhrase(query: string, source: Lang): Phrase | null {
  const q = normalize(query);
  if (q.length < 4) return null;
  let best: Phrase | null = null;
  let bestScore = 0;
  for (const p of PHRASES) {
    const t = normalize(p.text[source]);
    if (!t) continue;
    if (t === q) return p;
    if (t.includes(q) || q.includes(t)) {
      const score = Math.min(t.length, q.length) / Math.max(t.length, q.length);
      if (score > bestScore) {
        best = p;
        bestScore = score;
      }
    }
  }
  return bestScore >= 0.72 ? best : null;
}
