import type { Lang } from "./languages";

export type Term = {
  id: string;
  term: Record<Lang, string>;
  plain: Record<Lang, string>;
};

export const TERMS: Term[] = [
  {
    id: "hypertension",
    term: {
      en: "Hypertension",
      es: "Hipertensión",
      zh: "高血压",
      ar: "ارتفاع ضغط الدم",
      fr: "Hypertension",
      pt: "Hipertensão",
      vi: "Tăng huyết áp",
      ko: "고혈압",
      ht: "Tansyon wo",
      hi: "उच्च रक्तचाप",
    },
    plain: {
      en: "High blood pressure. The force of blood against artery walls is too high.",
      es: "Presión arterial alta. La sangre empuja con demasiada fuerza las arterias.",
      zh: "血压偏高，血液对血管壁的压力太大。",
      ar: "ضغط الدم مرتفع. الدم يضغط بقوة زائدة على جدران الشرايين.",
      fr: "Pression artérielle trop élevée. Le sang pousse trop fort sur les artères.",
      pt: "Pressão arterial alta. O sangue empurra demais as paredes das artérias.",
      vi: "Huyết áp cao. Máu đẩy mạnh lên thành mạch.",
      ko: "혈압이 높은 상태입니다. 피가 혈관 벽을 너무 세게 밀어냅니다.",
      ht: "Tansyon san an wo. San an pouse twò fò sou veso san yo.",
      hi: "ब्लड प्रेशर ऊँचा होना। रक्त धमनियों की दीवारों पर बहुत ज़ोर से दबता है।",
    },
  },
  {
    id: "diabetes",
    term: {
      en: "Diabetes",
      es: "Diabetes",
      zh: "糖尿病",
      ar: "السكري",
      fr: "Diabète",
      pt: "Diabetes",
      vi: "Bệnh đái tháo đường",
      ko: "당뇨병",
      ht: "Dyabèt",
      hi: "मधुमेह",
    },
    plain: {
      en: "A condition where blood sugar stays too high because the body cannot use insulin well.",
      es: "El azúcar en la sangre se mantiene alto porque el cuerpo no usa bien la insulina.",
      zh: "血糖长期偏高，身体不能很好地利用胰岛素。",
      ar: "حالة يبقى فيها سكر الدم مرتفعاً لأن الجسم لا يستخدم الإنسولين جيداً.",
      fr: "Le sucre dans le sang reste trop élevé car le corps n’utilise pas bien l’insuline.",
      pt: "O açúcar no sangue fica alto porque o corpo não usa bem a insulina.",
      vi: "Đường huyết cao vì cơ thể không dùng insulin tốt.",
      ko: "몸이 인슐린을 잘 쓰지 못해 혈당이 높은 상태입니다.",
      ht: "Sik nan san rete wo paske kò a pa itilize ensilin byen.",
      hi: "रक्त में शर्करा ऊँची रहती है क्योंकि शरीर इंसुलिन का सही उपयोग नहीं कर पाता।",
    },
  },
  {
    id: "mi",
    term: {
      en: "Myocardial infarction",
      es: "Infarto de miocardio",
      zh: "心肌梗死",
      ar: "احتشاء عضلة القلب",
      fr: "Infarctus du myocarde",
      pt: "Infarto do miocárdio",
      vi: "Nhồi máu cơ tim",
      ko: "심근경색",
      ht: "Atak kè",
      hi: "मायोकार्डियल इन्फार्क्शन",
    },
    plain: {
      en: "A heart attack. Blood flow to part of the heart muscle is blocked.",
      es: "Un ataque al corazón. Se bloquea el flujo de sangre a parte del músculo cardíaco.",
      zh: "心脏病发作。心脏某部分的血流被堵住了。",
      ar: "نوبة قلبية. يتوقف تدفق الدم عن جزء من عضلة القلب.",
      fr: "Une crise cardiaque. Le sang n’arrive plus à une partie du muscle cardiaque.",
      pt: "Um ataque do coração. O sangue não chega a uma parte do músculo cardíaco.",
      vi: "Cơn đau tim. Máu không tới được một phần cơ tim.",
      ko: "심장마비입니다. 심장 근육 일부로 가는 혈류가 막힌 상태입니다.",
      ht: "Yon atak kè. San pa rive nan yon pati nan misk kè a.",
      hi: "दिल का दौरा। हृदय की मांसपेशी के एक हिस्से तक रक्त नहीं पहुँच पाता।",
    },
  },
  {
    id: "stroke",
    term: {
      en: "Stroke",
      es: "Accidente cerebrovascular",
      zh: "中风",
      ar: "سكتة دماغية",
      fr: "Accident vasculaire cérébral",
      pt: "AVC",
      vi: "Đột quỵ",
      ko: "뇌졸중",
      ht: "Atak serebral",
      hi: "स्ट्रोक",
    },
    plain: {
      en: "A brain attack. Blood flow to part of the brain stops, so that part can be damaged.",
      es: "El flujo de sangre a una parte del cerebro se detiene y esa parte puede dañarse.",
      zh: "脑部突然缺血，那一部分大脑可能受损。",
      ar: "يتوقف تدفق الدم عن جزء من الدماغ فيتضرر.",
      fr: "Le sang n’arrive plus à une partie du cerveau, qui peut être endommagée.",
      pt: "O sangue para de chegar a uma parte do cérebro, que pode ser danificada.",
      vi: "Máu không tới một phần não, phần đó có thể bị tổn thương.",
      ko: "뇌로 가는 혈류가 끊겨 그 부위가 손상될 수 있습니다.",
      ht: "San sispann rive nan yon pati nan sèvo a, kidonk pati sa a ka domaje.",
      hi: "मस्तिष्क के एक हिस्से तक रक्त रुक जाता है, जिससे नुकसान हो सकता है।",
    },
  },
  {
    id: "fracture",
    term: {
      en: "Fracture",
      es: "Fractura",
      zh: "骨折",
      ar: "كسر",
      fr: "Fracture",
      pt: "Fratura",
      vi: "Gãy xương",
      ko: "골절",
      ht: "Zo kase",
      hi: "फ्रैक्चर",
    },
    plain: {
      en: "A broken bone.",
      es: "Un hueso roto.",
      zh: "骨头断了。",
      ar: "عظم مكسور.",
      fr: "Un os cassé.",
      pt: "Um osso quebrado.",
      vi: "Xương bị gãy.",
      ko: "뼈가 부러진 것입니다.",
      ht: "Yon zo ki kase.",
      hi: "हड्डी टूटना।",
    },
  },
  {
    id: "anesthesia",
    term: {
      en: "Anesthesia",
      es: "Anestesia",
      zh: "麻醉",
      ar: "تخدير",
      fr: "Anesthésie",
      pt: "Anestesia",
      vi: "Gây mê / gây tê",
      ko: "마취",
      ht: "Anestezi",
      hi: "एनेस्थीसिया",
    },
    plain: {
      en: "Medicine that stops you from feeling pain during a procedure. You may stay awake or go to sleep.",
      es: "Medicina que evita el dolor durante un procedimiento. Puede estar despierto o dormido.",
      zh: "做检查或手术时用来止痛的药。您可能醒着，也可能睡着。",
      ar: "دواء يمنع الشعور بالألم أثناء الإجراء. قد تبقى مستيقظاً أو تنام.",
      fr: "Un médicament qui empêche de sentir la douleur. Vous pouvez rester éveillé ou dormir.",
      pt: "Remédio que impede a dor durante o procedimento. Você pode ficar acordado ou dormir.",
      vi: "Thuốc làm hết đau khi làm thủ thuật. Bạn có thể tỉnh hoặc ngủ.",
      ko: "시술 중 통증을 못 느끼게 하는 약입니다. 깨어 있거나 잠들 수 있습니다.",
      ht: "Medikaman ki anpeche ou santi doulè pandan pwosedi a. Ou ka rete reveye oswa dòmi.",
      hi: "प्रक्रिया के दौरान दर्द न हो, इसके लिए दवा। आप जाग सकते हैं या सो सकते हैं।",
    },
  },
  {
    id: "iv",
    term: {
      en: "Intravenous (IV)",
      es: "Intravenoso (IV)",
      zh: "静脉输液",
      ar: "وريدي",
      fr: "Intraveineux (IV)",
      pt: "Intravenoso (soro)",
      vi: "Truyền tĩnh mạch",
      ko: "정맥주사",
      ht: "Pèfizyon (IV)",
      hi: "इंट्रावीनस (आईवी)",
    },
    plain: {
      en: "A thin tube in a vein that gives fluid or medicine directly into the blood.",
      es: "Un tubito en una vena que entrega líquido o medicina directo a la sangre.",
      zh: "扎在静脉里的细管，把液体或药物直接送进血液。",
      ar: "أنبوب رفيع في الوريد يعطي سوائل أو دواء مباشرة إلى الدم.",
      fr: "Un petit tuyau dans une veine qui donne du liquide ou un médicament dans le sang.",
      pt: "Um tubinho na veia que coloca líquido ou remédio direto no sangue.",
      vi: "Ống nhỏ trong tĩnh mạch để đưa dịch hoặc thuốc vào máu.",
      ko: "혈관에 가는 관을 넣어 수액이나 약을 바로 넣는 것입니다.",
      ht: "Yon ti tib nan venn ki bay likid oswa medikaman dirèkteman nan san an.",
      hi: "नस में एक पतली नली जिससे दवा या तरल सीधे रक्त में जाता है।",
    },
  },
  {
    id: "antibiotics",
    term: {
      en: "Antibiotics",
      es: "Antibióticos",
      zh: "抗生素",
      ar: "مضادات حيوية",
      fr: "Antibiotiques",
      pt: "Antibióticos",
      vi: "Kháng sinh",
      ko: "항생제",
      ht: "Antibyotik",
      hi: "एंटीबायोटिक",
    },
    plain: {
      en: "Medicine that kills bacteria. It does not treat viruses like a cold.",
      es: "Medicina que mata bacterias. No sirve para virus como un resfriado.",
      zh: "杀死细菌的药。对感冒这类病毒没用。",
      ar: "دواء يقتل البكتيريا. لا يعالج الفيروسات مثل الزكام.",
      fr: "Un médicament qui tue les bactéries. Il ne soigne pas les virus comme un rhume.",
      pt: "Remédio que mata bactérias. Não trata vírus como um resfriado.",
      vi: "Thuốc diệt vi khuẩn. Không chữa virus như cảm lạnh.",
      ko: "세균을 죽이는 약입니다. 감기 같은 바이러스에는 듣지 않습니다.",
      ht: "Medikaman ki touye bakteri. Li pa trete viris tankou yon grip.",
      hi: "बैक्टीरिया मारने की दवा। सर्दी जैसे वायरस पर काम नहीं करती।",
    },
  },
  {
    id: "npo",
    term: {
      en: "NPO (nothing by mouth)",
      es: "Nada por boca",
      zh: "禁食禁水",
      ar: "لا شيء عن طريق الفم",
      fr: "À jeun (rien par la bouche)",
      pt: "Nada pela boca",
      vi: "Không ăn uống qua miệng",
      ko: "금식 (입으로 아무것도 안 먹음)",
      ht: "Pa manje ni bwè anyen",
      hi: "मुँह से कुछ न खाएँ-पिएँ",
    },
    plain: {
      en: "Do not eat or drink anything, including water, until staff says it is safe.",
      es: "No coma ni beba nada, ni agua, hasta que el personal diga que es seguro.",
      zh: "在医护说可以之前，不要吃喝任何东西，包括水。",
      ar: "لا تأكل ولا تشرب أي شيء بما في ذلك الماء حتى يقول الطاقم إن ذلك آمن.",
      fr: "Ne mangez ni ne buvez rien, même pas de l’eau, jusqu’à ce que l’équipe le permette.",
      pt: "Não coma nem beba nada, nem água, até a equipe dizer que é seguro.",
      vi: "Không ăn uống gì, kể cả nước, cho đến khi nhân viên cho phép.",
      ko: "직원이 괜찮다고 할 때까지 물 포함해 아무것도 드시지 마세요.",
      ht: "Pa manje ni bwè anyen, menm dlo, jiskaske anplwaye yo di li an sekirite.",
      hi: "स्टाफ अनुमति देने तक पानी सहित कुछ भी न खाएँ-पिएँ।",
    },
  },
  {
    id: "consent",
    term: {
      en: "Informed consent",
      es: "Consentimiento informado",
      zh: "知情同意",
      ar: "موافقة مستنيرة",
      fr: "Consentement éclairé",
      pt: "Consentimento informado",
      vi: "Đồng thuận sau khi được giải thích",
      ko: "사전 동의",
      ht: "Konsantman enfòme",
      hi: "सूचित सहमति",
    },
    plain: {
      en: "You hear the plan, the risks, and the choices, then you say yes or no.",
      es: "Le explican el plan, los riesgos y las opciones, y usted dice sí o no.",
      zh: "先听清楚方案、风险和选择，然后您决定同意或拒绝。",
      ar: "تسمع الخطة والمخاطر والخيارات ثم تقول نعم أو لا.",
      fr: "On vous explique le projet, les risques et les choix, puis vous dites oui ou non.",
      pt: "Você ouve o plano, os riscos e as opções, e diz sim ou não.",
      vi: "Bạn được nghe kế hoạch, rủi ro và lựa chọn, rồi nói có hoặc không.",
      ko: "계획·위험·선택지를 들은 뒤 예 또는 아니요라고 하는 것입니다.",
      ht: "Yo eksplike ou plan an, risk yo, ak chwa yo, epi ou di wi oswa non.",
      hi: "योजना, जोखिम और विकल्प सुनकर आप हाँ या ना कहते हैं।",
    },
  },
  {
    id: "bp",
    term: {
      en: "Blood pressure",
      es: "Presión arterial",
      zh: "血压",
      ar: "ضغط الدم",
      fr: "Tension artérielle",
      pt: "Pressão arterial",
      vi: "Huyết áp",
      ko: "혈압",
      ht: "Tansyon",
      hi: "रक्तचाप",
    },
    plain: {
      en: "How hard the blood pushes on the walls of your arteries. Two numbers: the higher one when the heart squeezes.",
      es: "Qué tan fuerte empuja la sangre las arterias. Son dos números: el más alto cuando el corazón se contrae.",
      zh: "血液对血管壁的压力。有两个数字，高的那个是心脏收缩时的压力。",
      ar: "مدى قوة دفع الدم لجدران الشرايين. رقمان: الأعلى عندما ينقبض القلب.",
      fr: "La force du sang dans les artères. Deux chiffres : le plus haut quand le cœur se contracte.",
      pt: "A força do sangue nas artérias. Dois números: o maior quando o coração se contrai.",
      vi: "Lực máu đẩy lên thành mạch. Hai số: số cao khi tim co.",
      ko: "피가 혈관 벽을 미는 힘입니다. 숫자 두 개 중 큰 값은 심장이 수축할 때입니다.",
      ht: "Ki jan san an pouse sou veso yo. De nimewo: pi wo a se lè kè a sere.",
      hi: "रक्त धमनियों पर कितना दबाव डालता है। दो संख्याएँ: बड़ी संख्या दिल के सिकुड़ने पर।",
    },
  },
  {
    id: "ct",
    term: {
      en: "CT scan",
      es: "Tomografía (TAC)",
      zh: "CT 扫描",
      ar: "أشعة مقطعية",
      fr: "Scanner (TDM)",
      pt: "Tomografia (TC)",
      vi: "Chụp CT",
      ko: "CT 촬영",
      ht: "Eskanè CT",
      hi: "सीटी स्कैन",
    },
    plain: {
      en: "A special X-ray machine that takes many pictures to make a 3D view of the inside of the body.",
      es: "Una máquina de rayos X especial que toma muchas fotos para ver el interior del cuerpo en 3D.",
      zh: "一种特殊的 X 光，拍很多张片子组成身体内部的立体图像。",
      ar: "جهاز أشعة خاص يلتقط صوراً كثيرة لعمل صورة ثلاثية الأبعاد لداخل الجسم.",
      fr: "Un appareil à rayons X qui prend beaucoup d’images pour voir l’intérieur du corps en 3D.",
      pt: "Um aparelho de raio X especial que tira muitas fotos para ver o corpo por dentro em 3D.",
      vi: "Máy X-quang đặc biệt chụp nhiều ảnh để xem bên trong cơ thể theo 3D.",
      ko: "엑스레이를 여러 장 찍어 몸 속을 입체적으로 보는 검사입니다.",
      ht: "Yon machin reyon X espesyal ki pran anpil foto pou wè andedan kò a an 3D.",
      hi: "एक खास एक्स-रे मशीन जो शरीर के अंदर का 3डी चित्र बनाती है।",
    },
  },
  {
    id: "mri",
    term: {
      en: "MRI",
      es: "Resonancia magnética",
      zh: "核磁共振",
      ar: "الرنين المغناطيسي",
      fr: "IRM",
      pt: "Ressonância magnética",
      vi: "Cộng hưởng từ (MRI)",
      ko: "MRI",
      ht: "Rezonans mayetik",
      hi: "एमआरआई",
    },
    plain: {
      en: "A tunnel-like magnet that makes detailed pictures of organs and tissues. No regular X-ray radiation.",
      es: "Un imán en forma de túnel que toma fotos detalladas de órganos. No usa radiación de rayos X habitual.",
      zh: "像隧道的磁体，拍器官和组织的细致图像。一般不用普通 X 光辐射。",
      ar: "مغناطيس على شكل نفق يلتقط صوراً تفصيلية للأعضاء. لا يستخدم إشعاع الأشعة السينية العادي.",
      fr: "Un aimant en tunnel qui fait des images détaillées. Pas de rayons X habituels.",
      pt: "Um ímã em forma de túnel que tira fotos detalhadas. Sem radiação de raio X comum.",
      vi: "Nam châm hình ống chụp ảnh chi tiết cơ quan. Không dùng tia X thông thường.",
      ko: "터널형 자석으로 장기·조직을 자세히 찍습니다. 일반 엑스레이 방사선은 쓰지 않습니다.",
      ht: "Yon leman tankou yon tinèl ki fè foto detaye ògàn yo. Pa itilize reyon X nòmal.",
      hi: "सुरंग जैसा चुंबक जो अंगों की विस्तृत तस्वीर लेता है। सामान्य एक्स-रे विकिरण नहीं।",
    },
  },
  {
    id: "suture",
    term: {
      en: "Sutures",
      es: "Suturas / puntos",
      zh: "缝线",
      ar: "غرز",
      fr: "Sutures / points",
      pt: "Pontos",
      vi: "Chỉ khâu",
      ko: "봉합",
      ht: "Pwen",
      hi: "टांके",
    },
    plain: {
      en: "Stitches that hold a wound closed so it can heal.",
      es: "Puntos que cierran una herida para que sane.",
      zh: "把伤口缝合起来，好让它愈合。",
      ar: "غرز تُغلق الجرح حتى يلتئم.",
      fr: "Des fils qui ferment une plaie pour qu’elle cicatrise.",
      pt: "Pontos que fecham um corte para ele cicatrizar.",
      vi: "Chỉ khâu để khép vết thương cho lành.",
      ko: "상처를 닫아 아물게 하는 실입니다.",
      ht: "Pwen ki fèmen yon blesi pou li geri.",
      hi: "घाव बंद रखने वाले टांके ताकि वह भर सके।",
    },
  },
  {
    id: "discharge",
    term: {
      en: "Discharge",
      es: "Alta",
      zh: "出院",
      ar: "خروج من المستشفى",
      fr: "Sortie / retour à domicile",
      pt: "Alta",
      vi: "Xuất viện",
      ko: "퇴원",
      ht: "Soti lopital",
      hi: "डिस्चार्ज",
    },
    plain: {
      en: "You are well enough to leave the hospital or clinic, with a plan for home care.",
      es: "Está lo bastante bien para irse, con un plan de cuidados en casa.",
      zh: "身体情况允许离开医院或诊所，并带上居家护理计划。",
      ar: "أنت بصحة كافية لمغادرة المستشفى مع خطة للعناية في المنزل.",
      fr: "Vous êtes assez bien pour partir, avec un plan de soins à la maison.",
      pt: "Você está bem o bastante para ir embora, com um plano de cuidados em casa.",
      vi: "Đủ khỏe để về, kèm kế hoạch chăm sóc tại nhà.",
      ko: "집에서 관리할 계획을 갖고 병원이나 의원을 떠날 수 있을 만큼 회복된 상태입니다.",
      ht: "Ou byen ase pou ale, ak yon plan swen lakay.",
      hi: "आप अस्पताल छोड़ सकते हैं, घर पर देखभाल की योजना के साथ।",
    },
  },
];

export function searchTerms(query: string, lang: Lang): Term[] {
  const q = query.trim().toLowerCase();
  if (!q) return TERMS;
  return TERMS.filter((t) => {
    return LANG_VALUES(t, lang).some((s) => s.toLowerCase().includes(q));
  });
}

function LANG_VALUES(t: Term, lang: Lang) {
  return [t.term[lang], t.plain[lang], t.term.en, t.plain.en];
}
