/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as HistoryRouteImport } from "./routes/history";
import { Route as LearnRouteImport } from "./routes/learn";
import { Route as PainRouteImport } from "./routes/pain";
import { Route as PhrasesRouteImport } from "./routes/phrases";
import { Route as TalkRouteImport } from "./routes/talk";
import { Route as TermsRouteImport } from "./routes/terms";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const HistoryRoute = HistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => rootRouteImport,
} as any);
const LearnRoute = LearnRouteImport.update({
  id: "/learn",
  path: "/learn",
  getParentRoute: () => rootRouteImport,
} as any);
const PainRoute = PainRouteImport.update({
  id: "/pain",
  path: "/pain",
  getParentRoute: () => rootRouteImport,
} as any);
const PhrasesRoute = PhrasesRouteImport.update({
  id: "/phrases",
  path: "/phrases",
  getParentRoute: () => rootRouteImport,
} as any);
const TalkRoute = TalkRouteImport.update({
  id: "/talk",
  path: "/talk",
  getParentRoute: () => rootRouteImport,
} as any);
const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/history": typeof HistoryRoute;
  "/learn": typeof LearnRoute;
  "/pain": typeof PainRoute;
  "/phrases": typeof PhrasesRoute;
  "/talk": typeof TalkRoute;
  "/terms": typeof TermsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/history": typeof HistoryRoute;
  "/learn": typeof LearnRoute;
  "/pain": typeof PainRoute;
  "/phrases": typeof PhrasesRoute;
  "/talk": typeof TalkRoute;
  "/terms": typeof TermsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/history": typeof HistoryRoute;
  "/learn": typeof LearnRoute;
  "/pain": typeof PainRoute;
  "/phrases": typeof PhrasesRoute;
  "/talk": typeof TalkRoute;
  "/terms": typeof TermsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/about" | "/history" | "/learn" | "/pain" | "/phrases" | "/talk" | "/terms";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/about" | "/history" | "/learn" | "/pain" | "/phrases" | "/talk" | "/terms";
  id:
    "__root__" | "/" | "/about" | "/history" | "/learn" | "/pain" | "/phrases" | "/talk" | "/terms";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  HistoryRoute: typeof HistoryRoute;
  LearnRoute: typeof LearnRoute;
  PainRoute: typeof PainRoute;
  PhrasesRoute: typeof PhrasesRoute;
  TalkRoute: typeof TalkRoute;
  TermsRoute: typeof TermsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/history": {
      id: "/history";
      path: "/history";
      fullPath: "/history";
      preLoaderRoute: typeof HistoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/learn": {
      id: "/learn";
      path: "/learn";
      fullPath: "/learn";
      preLoaderRoute: typeof LearnRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pain": {
      id: "/pain";
      path: "/pain";
      fullPath: "/pain";
      preLoaderRoute: typeof PainRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/phrases": {
      id: "/phrases";
      path: "/phrases";
      fullPath: "/phrases";
      preLoaderRoute: typeof PhrasesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/talk": {
      id: "/talk";
      path: "/talk";
      fullPath: "/talk";
      preLoaderRoute: typeof TalkRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/terms": {
      id: "/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HistoryRoute: HistoryRoute,
  LearnRoute: LearnRoute,
  PainRoute: PainRoute,
  PhrasesRoute: PhrasesRoute,
  TalkRoute: TalkRoute,
  TermsRoute: TermsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
